# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adjlist2matrix <- function(adj) {
    .Call(`_geomander_adjlist2matrix`, adj)
}

contiguity <- function(adj, group) {
    .Call(`_geomander_contiguity`, adj, group)
}

countconnections <- function(dm) {
    .Call(`_geomander_countconnections`, dm)
}

localgeary <- function(x, mat) {
    .Call(`_geomander_localgeary`, x, mat)
}

globalgeary <- function(x, mat) {
    .Call(`_geomander_globalgeary`, x, mat)
}

localgstar <- function(x, mat) {
    .Call(`_geomander_localgstar`, x, mat)
}

localmoran <- function(x, mat) {
    .Call(`_geomander_localmoran`, x, mat)
}

globalmoran <- function(x, mat) {
    .Call(`_geomander_globalmoran`, x, mat)
}

